insert into public.emotions (id, label, image, category, sort_order, is_active) values
  ('joyful', '기쁨', '/image/emotions/joyful.svg', 'joy', 1, true),
  ('happy', '행복', '/image/emotions/happy.svg', 'joy', 2, true),
  ('excited', '설렘', '/image/emotions/excited.svg', 'joy', 3, true),
  ('proud', '뿌듯함', '/image/emotions/joyful.svg', 'joy', 4, true),
  ('calm', '평온', '/image/emotions/calm.svg', 'calm', 11, true),
  ('relieved', '안도', '/image/emotions/calm.svg', 'calm', 12, true),
  ('comfortable', '여유', '/image/emotions/calm.svg', 'calm', 13, true),
  ('stable', '안정', '/image/emotions/calm.svg', 'calm', 14, true),
  ('sad', '슬픔', '/image/emotions/sad.svg', 'sadness', 21, true),
  ('hurt', '서운함', '/image/emotions/sad.svg', 'sadness', 22, true),
  ('loss', '상실감', '/image/emotions/sad.svg', 'sadness', 23, true),
  ('empty', '허전함', '/image/emotions/sad.svg', 'sadness', 24, true),
  ('anxious', '불안', '/image/emotions/anxious.svg', 'anxiety', 31, true),
  ('worried', '걱정', '/image/emotions/anxious.svg', 'anxiety', 32, true),
  ('nervous', '초조함', '/image/emotions/anxious.svg', 'anxiety', 33, true),
  ('scared', '두려움', '/image/emotions/scared.svg', 'anxiety', 34, true),
  ('angry', '분노', '/image/emotions/angry.svg', 'anger', 41, true),
  ('irritated', '짜증', '/image/emotions/angry.svg', 'anger', 42, true),
  ('unfair', '억울함', '/image/emotions/angry.svg', 'anger', 43, true),
  ('frustrated', '답답함', '/image/emotions/angry.svg', 'anger', 44, true),
  ('lonely', '외로움', '/image/emotions/confused.svg', 'loneliness', 51, true),
  ('isolated', '소외감', '/image/emotions/confused.svg', 'loneliness', 52, true),
  ('missing', '그리움', '/image/emotions/confused.svg', 'loneliness', 53, true),
  ('void', '공허함', '/image/emotions/confused.svg', 'loneliness', 54, true),
  ('tired', '피곤함', '/image/emotions/disappointed.svg', 'fatigue', 61, true),
  ('lethargic', '무기력', '/image/emotions/disappointed.svg', 'fatigue', 62, true),
  ('exhausted', '지침', '/image/emotions/disappointed.svg', 'fatigue', 63, true),
  ('burnout', '번아웃', '/image/emotions/disappointed.svg', 'fatigue', 64, true),
  ('ashamed', '부끄러움', '/image/emotions/scared.svg', 'reflection', 71, true),
  ('guilty', '죄책감', '/image/emotions/scared.svg', 'reflection', 72, true),
  ('regret', '후회', '/image/emotions/scared.svg', 'reflection', 73, true),
  ('embarrassed', '민망함', '/image/emotions/scared.svg', 'reflection', 74, true),
  ('confused', '혼란', '/image/emotions/confused.svg', 'confusion', 81, true),
  ('stuck', '막막함', '/image/emotions/confused.svg', 'confusion', 82, true),
  ('sensitive', '예민함', '/image/emotions/confused.svg', 'confusion', 83, true),
  ('blank', '멍함', '/image/emotions/confused.svg', 'confusion', 84, true)
on conflict (id) do update set
  label = excluded.label,
  image = excluded.image,
  category = excluded.category,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
